### ISSUE TITLE
Option for registering all presses as “single press”

### ISSUE THREAD

**Issue by DanielSmith1239** [shanemcw/homebridge-amazondash-mac#7]
Hello, would you be able to add a config checkbox for each button that allows for registering all presses as “single press”es?

**Comment by DanielSmith1239** [comment]
Thanks, that’s what I’ve been doing. For some reason if I press the button a second time within a few seconds of the first press, it doesn’t seem to register the second press at all (either as a single or double), so I’m hoping this might help.

**Comment by shanemcw** [comment]
@DanielSmith1239 Ah! Thanks so much for the additional information!

There is a limitation to the operation of the Amazon Dash button as a HomeKit button—on a press, the button tries to connect to a wifi network (that will fail). During this attempt, the LED slowly pulses a yellow-white while it is trying, then blinks red to report the failure.

During this (approximately 9 seconds) attempt and while the lights are lit, button presses are ignored.

To get a double press, you'll have to wait until the lights go dark before pressing, and wait no longer than 15 seconds. After 15 seconds, a press will register as a single press again.

The feature to disable double/second-press functionality only applies between the lights going dark and 15 seconds after, so it is a bit of a special case during those seconds.

Thanks again!

Apologies that there's nothing we can do during that 9-second "lights lit" process when the device is ignoring button presses while attempting and failing to connect to the network!

**Comment by DanielSmith1239** [comment]
I see. I found with hacking the device first (see https://github.com/Nekmo/amazon-dash) causes the light to blink for around half the time, so that helps.

Thanks for the great project!

**Comment by shanemcw** [comment]
Thanks @DanielSmith1239! I presume the Nekmo hack step to configure the button now allows it to connect to the wireless network—therefore it does not fail. I presume trying and succeeding will resolve faster (and free up the button for a another press) than trying and failing on a timeout! Thanks again!

**Comment by shanemcw** [comment]
Thanks @DanielSmith1239 —an "opt-in" for "register a second press as a double press" will be out in the next release.
I'm also thinking about adding an opt-in feature to allow a remote "push" of a button as a web API.

**Comment by shanemcw** [comment]
@DanielSmith1239

**Release 3.0.0 Beta 2** is now available for testing.

**Comment by DanielSmith1239** [comment]
Thanks!

**Comment by shanemcw** [comment]
@DanielSmith1239 any feedback on the beta releases is appreciated!

**Comment by DanielSmith1239** [comment]
Sorry, I’ve been super busy with work and other projects, but I’ll try to check it out soon!

**Comment by shanemcw** [comment]
This optional feature is implemented in version 3.0.0.
